### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by miaotony** [miaotony/NUAA_LibraryFlow#1]
- [x] Crawler based on library booking system  
- [x] API backend, JSON data with all areas      
- [x] Crawler, multiprocessing   
- [x] Crawler based on serverless platform, e.g. Github Action(?)  
- [ ] Frontend based on Vue.js(?)    
- [ ] Visualization based on frontend
